language: rust

rust:
  - nightly

sudo: 9000

os:
  - linux
  - osx

dist: trusty

addons:
  apt:
    sources:
      # Provides newer gcc.
      - ubuntu-toolchain-r-test
      # Provides libclang 3.9.
      - llvm-toolchain-trusty-3.9
    packages:
      - autoconf2.13
      # bindgen requires libclang >= 3.9.
      - clang-3.9
      # SpiderMonkey needs gcc >= 4.9.
      - gcc-5
      - g++-5

env:
  - FEATURES=""
  - FEATURES="--features debugmozjs"

before_install:
  - source .travis/before_install.sh

script:
  - .travis/script.sh

notifications:
  webhooks: http://build.servo.org:54856/travis

cache: ccache
